-- 요구사항 명세서 기준 Supabase / PostgreSQL 스키마
-- Supabase Dashboard > SQL Editor에서 실행

-- 1) 프로필 (Auth 연동): member_id / cnsler_id 구분
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('member', 'counsellor')),
  member_id TEXT,
  cnsler_id TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- RLS: 본인만 읽기/수정
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "profiles_select_own" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "profiles_insert_own" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 2) 상담 매칭: cnsl_id로 member / counsellor 연결
CREATE TABLE IF NOT EXISTS public.consultations (
  cnsl_id BIGINT PRIMARY KEY,
  member_id TEXT NOT NULL,
  cnsler_id TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- RLS: 인증된 사용자는 조회만 (필요 시 정책 조정)
ALTER TABLE public.consultations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "consultations_select" ON public.consultations FOR SELECT TO authenticated USING (true);

-- 3) 채팅/요약 저장 (chat_msg)
CREATE TABLE IF NOT EXISTS public.chat_msg (
  chat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cnsl_id BIGINT NOT NULL,
  member_id VARCHAR NOT NULL,
  cnsler_id VARCHAR NOT NULL,
  role VARCHAR NOT NULL DEFAULT 'user',
  msg_data JSONB,
  summery TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.chat_msg ENABLE ROW LEVEL SECURITY;
CREATE POLICY "chat_msg_select" ON public.chat_msg FOR SELECT TO authenticated USING (true);
CREATE POLICY "chat_msg_insert" ON public.chat_msg FOR INSERT TO authenticated WITH CHECK (true);

-- 예시: 상담 1건 등록 (테스트용)
-- INSERT INTO public.consultations (cnsl_id, member_id, cnsler_id) VALUES (1, 'm_xxx', 'c_yyy');
